### ISSUE TITLE
Dynamic Segment Support?

### ISSUE THREAD

**Issue by sdavies** [reasoncorp/dossier-segmenter#1]
Is there any plan or any way to dynamically group by or segment a dossier report?

Maybe something like:

``` ruby

class CuteAnimalsReport < Dossier::Report
  class Segmenter < Dossier::Segmenter
    segment :group, display_name: -> { @group_option == :family ? 'Family' : 'Domestic' }, group_by: { @group_option == :family ? :family : :domestic }
  end
end
```

**Comment by hrmrebecca** [comment]
Hi! I apologize for the delayed response.
There is currently nothing in segmenter that allows one to easily use dynamic segmentation.
We've dealt with it here locally by overriding the segmenter method, and in that method, deciding  which segment to run and creating an instance of the corresponding class.  We also define a 'GrandpaSegmenter' module - which binds and calls the unsullied version of the segmenter method - and then include it in each class.  

``` ruby
class CuteAnimalsReport < Dossier::Report
  # ...
  def segmenter
    klass = family ? KittenReport : PuppyReport
    @segmenter ||= klass.new(options).segmenter
  end

  module GrandpaSegmenter
    def segmenter
      Dossier::Report.instance_method(:segmenter).bind(self).call
    end
  end

  class KittenReport < self
    include GrandpaSegmenter
    class Segmenter < Dossier::Segmenter
      segment :fluffiness
    end
  end

  class PuppyReport < self
    include GrandpaSegmenter
    class Segmenter < Dossier::Segmenter
      segment :tail_length
    end
  end
end
```

**Comment by sdavies** [comment]
Thanks Rebecca,

I ended up doing almost exactly the same thing.
